client_secrets_file: "C:\\Users\\your_user\\.google\\oauth.keys.json"
token_file: "C:\\Users\\your_user\\.google\\token.json"
backup_dir: "C:\\Users\\your_user\\.google\\backups"
log_file: "C:\\Users\\your_user\\.google\\mcp_operations.log"
mcp_auth_token: "change_me"
scopes:
  - "https://www.googleapis.com/auth/spreadsheets"
  - "https://www.googleapis.com/auth/drive"
  - "https://www.googleapis.com/auth/script.projects"
  - "https://www.googleapis.com/auth/script.deployments"
  - "https://www.googleapis.com/auth/documents"
  - "https://www.googleapis.com/auth/gmail.modify"
  - "https://www.googleapis.com/auth/calendar"
  - "https://www.googleapis.com/auth/gmail.readonly"
